 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/waitinglists", type: :request do
  
  # Waitinglist. As you add validations to Waitinglist, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Waitinglist.create! valid_attributes
      get waitinglists_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      waitinglist = Waitinglist.create! valid_attributes
      get waitinglist_url(waitinglist)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_waitinglist_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      waitinglist = Waitinglist.create! valid_attributes
      get edit_waitinglist_url(waitinglist)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Waitinglist" do
        expect {
          post waitinglists_url, params: { waitinglist: valid_attributes }
        }.to change(Waitinglist, :count).by(1)
      end

      it "redirects to the created waitinglist" do
        post waitinglists_url, params: { waitinglist: valid_attributes }
        expect(response).to redirect_to(waitinglist_url(Waitinglist.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Waitinglist" do
        expect {
          post waitinglists_url, params: { waitinglist: invalid_attributes }
        }.to change(Waitinglist, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post waitinglists_url, params: { waitinglist: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested waitinglist" do
        waitinglist = Waitinglist.create! valid_attributes
        patch waitinglist_url(waitinglist), params: { waitinglist: new_attributes }
        waitinglist.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the waitinglist" do
        waitinglist = Waitinglist.create! valid_attributes
        patch waitinglist_url(waitinglist), params: { waitinglist: new_attributes }
        waitinglist.reload
        expect(response).to redirect_to(waitinglist_url(waitinglist))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        waitinglist = Waitinglist.create! valid_attributes
        patch waitinglist_url(waitinglist), params: { waitinglist: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested waitinglist" do
      waitinglist = Waitinglist.create! valid_attributes
      expect {
        delete waitinglist_url(waitinglist)
      }.to change(Waitinglist, :count).by(-1)
    end

    it "redirects to the waitinglists list" do
      waitinglist = Waitinglist.create! valid_attributes
      delete waitinglist_url(waitinglist)
      expect(response).to redirect_to(waitinglists_url)
    end
  end
end
